name: CI

on:
  push:
  pull_request:

jobs:
  python-api:
    name: Python API
    runs-on: ubuntu-latest
    if: ${{ hashFiles('services/api/pyproject.toml') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pipx install poetry || python -m pip install --user poetry
      - name: Install deps (no-root)
        working-directory: services/api
        run: |
          poetry --version || python -m poetry --version
          poetry install --no-root
      - name: Lint
        working-directory: services/api
        run: |
          poetry run ruff check .
          poetry run black --check .
      - name: Test (coverage ≥80%)
        working-directory: services/api
        run: |
          poetry run pytest --cov=app --cov-report=term-missing --cov-fail-under=80

  go-service:
    name: Go Service
    runs-on: ubuntu-latest
    if: ${{ hashFiles('services/api/src/go_service/go.mod') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        working-directory: services/api/src/go_service
        run: go build -v ./...
      - name: Test
        working-directory: services/api/src/go_service
        run: go test -v ./...
