name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  PYTHON_VERSION: "3.11"
  GO_VERSION: "1.22"

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          cd services/api
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          cd services/api
          poetry run pytest --cov=src --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./services/api/coverage.xml
        continue-on-error: true

  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build Go service
        run: |
          cd services/api/src/go_service
          go build -v ./.
      - name: Test Go service
        run: |
          cd services/api/src/go_service
          go test -v ./.

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run security scan
        run: |
          cd services/api
          pip install safety
          poetry export -f requirements.txt | safety check --stdin
